### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by DannyBen** [siebertm/parse-cron#21]
I know the last commit is some time ago, but is there a chance this is still maintained?
There are some issues and I am wondering if I should report or fork and fix on my own.

**Comment by siebertm** [comment]
I'm a bit busy at times and don't have plans to add stuff myself (it works
perfectly for our needs, we're using it actively)
But if you have issues you'd like to fix, I'll happily review and merge
them!
Danny Ben Shitrit <notifications@github.com> schrieb am Mi., 19. Aug. 2015
um 20:49:

**Comment by DannyBen** [comment]
Ok - I have forked it will see if I can change some things.
