### ISSUE TITLE
support for 2nd Monday of the month MON#2

### ISSUE THREAD

**Issue by arkarkark** [siebertm/parse-cron#22]
from the tests it doesn't look like this syntax is supported

0 0 12 ? 1/1 MON#2 *

to mean midnight on the 2nd Monday of every month.

it was generated by http://www.cronmaker.com/

**Comment by siebertm** [comment]
Currently, I don't have the time to expand to more syntax (because it works for what we use it for and doesn't have any itches I need to scratch)

Feel free to create a PR though, I'll gladly review & merge it!

**Comment by arkarkark** [comment]
Thanks @siebertm, turns out this is solvable with current functionality

`30 8 1-7 * 1`

and 8-14 for second etc...
