### ISSUE TITLE
parse-cron supports timezones ? 

### ISSUE THREAD

**Issue by bilby91** [siebertm/parse-cron#27]

**Comment by DannyBen** [comment]
I am also interested in this. What are the steps needed to make the result timezone-aware.

EDIT:
I think I found the answer. `CronParser.new` [receives a second argument](https://github.com/siebertm/parse-cron/blob/master/lib/cron_parser.rb#L54) `time_source` which is the class that is used as a basis, so it seems.

So, in rails, this line uses the currently configured time zone

``` ruby
CronParser.new("0 8 * * *", Time.zone).next
```

**Comment by siebertm** [comment]
Time zones are hard. Especially hard to get correct (our company builds a calendar, so unfortunately, I know that I'm right).

I rather would not go down that path given that I barely have the time to respond here. Though if anyone wants to explore in that directeion: feel free to attach a PR!

Great to hear that setting the `time_source` works for you!
